### ISSUE TITLE
Metrilyx does not show in Browser

### ISSUE THREAD

**Issue by enricoxx** [Ticketmaster/metrilyx-2.0#91]
I installed the .deb package in Ubuntu 14.04 Server.
When I try to get the Metrilyx site in the Browser the site does not appear and I get the following error (metrilyx-modelmanger.log).

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 45, in load_middleware
    mw_class = import_by_path(middleware_path)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 26, in import_by_path
    sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 21, in import_by_path
    module = import_module(module_path)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/reversion/__init__.py", line 11, in <module>
    from reversion.revisions import default_revision_manager, revision_context_manager, VersionAdapter
  File "/usr/local/lib/python2.7/dist-packages/reversion/revisions.py", line 21, in <module>
    from reversion.models import Revision, Version, has_int_pk, pre_revision_commit, post_revision_commit
  File "/usr/local/lib/python2.7/dist-packages/reversion/models.py", line 6, in <module>
    from django.contrib.contenttypes.fields import GenericForeignKey
django.core.exceptions.ImproperlyConfigured: Error importing module reversion.middleware: "No module named fields"
[pid: 2083|app: 0|req: 1/2] 95.91.224.223 () {40 vars in 598 bytes} [Tue May 12 13:51:26 2015] GET /api/graphmaps => generated 0 bytes in 117 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)

**Comment by enricoxx** [comment]
Problem was django version 1.8 . I had success with django 1.6.5 .
