### ISSUE TITLE
Web Page has only "Drag metrics here from search"

### ISSUE THREAD

**Issue by shujamughal** [Ticketmaster/metrilyx-2.0#97]
Hi,

I have installed as mentioned in the document on ubuntu 14.14 but on the web page, its just showing "Drag metrics here from search" nothing else.

here is chrome console output
---------------------------
Failed to load resource: the server responded with a status of 500 (Internal Server Error)  http://myserver/api/config 
Object
Error: [$injector:unpr] http://errors.angularjs.org/1.2.9/$injector/unpr?p0=ConfigurationProvider%20%3C-%20Configuration%20%3C-%20Metrics%20%3C-%20metricSearchPanelDirective
    at Error (native)
    at http://myserver/libs/angular/1.2.9/angular.min.js:6:449
    at http://myserver/libs/angular/1.2.9/angular.min.js:32:125
    at Object.c [as get] (http://myserver/libs/angular/1.2.9/angular.min.js:30:200)
    at http://myserver/libs/angular/1.2.9/angular.min.js:32:193
    at c (http://myserver/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://myserver/libs/angular/1.2.9/angular.min.js:30:417)
    at http://myserver/libs/angular/1.2.9/angular.min.js:32:211
    at c (http://myserver/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://myserver/libs/angular/1.2.9/angular.min.js:30:417)
Error: [$injector:unpr] http://errors.angularjs.org/1.2.9/$injector/unpr?p0=ConfigurationProvider%2…uration%20%3C-%20WsHighstockGraphHelper%20%3C-%20wsHighstockGraphDirective
    at Error (native)
    at http://myserver/libs/angular/1.2.9/angular.min.js:6:449
    at http://myserver/libs/angular/1.2.9/angular.min.js:32:125
    at Object.c [as get] (http://myserver/libs/angular/1.2.9/angular.min.js:30:200)
    at http://myserver/libs/angular/1.2.9/angular.min.js:32:193
    at c (http://myserver/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://myserver/libs/angular/1.2.9/angular.min.js:30:417)
    at http://myserver/libs/angular/1.2.9/angular.min.js:32:211
    at c (http://myserver/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://myserver/libs/angular/1.2.9/angular.min.js:30:417)
Error: [$injector:unpr] http://errors.angularjs.org/1.2.9/$injector/unpr?p0=ConfigurationProvider%20%3C-%20Configuration
    at Error (native)
    at http://myserver/libs/angular/1.2.9/angular.min.js:6:449
    at http://myserver/libs/angular/1.2.9/angular.min.js:32:125
    at Object.c [as get] (http://myserver/libs/angular/1.2.9/angular.min.js:30:200)
    at http://myserver/libs/angular/1.2.9/angular.min.js:32:193
    at c (http://myserver/libs/angular/1.2.9/angular.min.js:30:200)
    at d (http://myserver/libs/angular/1.2.9/angular.min.js:30:417)
    at Object.instantiate (http://myserver/libs/angular/1.2.9/angular.min.js:31:80)
    at http://myserver/libs/angular/1.2.9/angular.min.js:61:486
    at link (http://myserver/libs/angular/1.2.9/angular-route.min.js:7:208) <div ng-view="" class="ng-scope">
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

--------------------------

Can you please help me how to fix it?

Thanks
Shuja

**Comment by lufenghuan** [comment]
I have the similar problem. 

From  metrilyx-modelmanager.log
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/metrilyx/wsgi.py", line 43, in <module>
    application = get_wsgi_application()
  File "/opt/metrilyx/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/opt/metrilyx/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/metrilyx/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/opt/metrilyx/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/metrilyx/usr/local/lib/python2.7/dist-packages/reversion/__init__.py", line 12, in <module>
    from reversion.admin import VersionAdmin
  File "/opt/metrilyx/usr/local/lib/python2.7/dist-packages/reversion/admin.py", line 31, in <module>
    class VersionAdmin(admin.ModelAdmin):
  File "/opt/metrilyx/usr/local/lib/python2.7/dist-packages/reversion/admin.py", line 382, in VersionAdmin
    @transaction.commit_on_success
AttributeError: 'module' object has no attribute 'commit_on_success'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***

```

**Comment by euforia** [comment]
@shujamughal : Looks like there some misconfiguration.  Take a look at the nginx error logs (/var/log/nginx/ i think).  That should provide more background.  Also make sure your FQDN is resolvable.

**Comment by euforia** [comment]
@lufenghuan : Yours is having issues with the version of the `reversions` python module. Could be an older version. Can you provide me with more info ? i.e os, distribution, python version etc.

**Comment by lufenghuan** [comment]
Hi, 
I am running on Ubuntu14.04.1 LTS, with Python2.7, metrilyx-2.0_2.5.1-19_amd64.deb. 

Thanks!

**Comment by euforia** [comment]
@lufenghuan - Would you mind trying this installation method here: https://github.com/Ticketmaster/metrilyx-2.0/blob/master/docs/Installation.md#installation ?

I have a feeling the .deb might be bad.

**Comment by euforia** [comment]
Closing.  Feel free to re-open if necessary.

**Comment by sadoyan** [comment]
Hi, 
I am running on Ubuntu14.04.1 LTS, with Python2.7 and used installl method described here : 
https://github.com/Ticketmaster/metrilyx-2.0/blob/master/docs/Installation.md#installation 
I have exact same problem, and in my case model-manager refuses to start. 

/etc/init.d/metrilyx-modelmanager: 39: /etc/init.d/metrilyx-modelmanager: --ini: not found
